function H_mag = W_calcHm(MagX,MagY,MagZ,q0,q1,q2,q3)
%W_CALCHM
%    H_MAG = W_CALCHM(MAGX,MAGY,MAGZ,Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    04-Jan-2019 16:54:59

t2 = MagY.*q0.*2.0;
t3 = MagZ.*q1.*2.0;
t15 = MagX.*q3.*2.0;
t4 = t2+t3-t15;
t5 = MagY.*q1.*2.0;
t6 = MagX.*q1.*2.0;
t7 = MagY.*q2.*2.0;
t8 = MagZ.*q3.*2.0;
t9 = t6+t7+t8;
t10 = MagX.*q0.*2.0;
t11 = MagY.*q3.*2.0;
t12 = MagX.*q2.*2.0;
t13 = MagZ.*q0.*2.0;
t14 = -t5+t12+t13;
t16 = MagZ.*q2.*2.0;
H_mag = reshape([t10+t11-MagZ.*q2.*2.0,t4,t14,t9,t14,-t2-t3+t15,t5-MagX.*q2.*2.0-MagZ.*q0.*2.0,t9,t10+t11-t16,t4,-t10-t11+t16,t9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,7]);
