function Q = W_calcQ(daxCov,dayCov,dazCov,q0,q1,q2,q3)
%W_CALCQ
%    Q = W_CALCQ(DAXCOV,DAYCOV,DAZCOV,Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    04-Jan-2019 16:54:58

t2 = dayCov.*q2.*q3.*(1.0./4.0);
t3 = t2-daxCov.*q0.*q1.*(1.0./4.0)-dazCov.*q2.*q3.*(1.0./4.0);
t4 = q3.^2;
t5 = q2.^2;
t6 = dazCov.*q1.*q3.*(1.0./4.0);
t7 = t6-daxCov.*q1.*q3.*(1.0./4.0)-dayCov.*q0.*q2.*(1.0./4.0);
t8 = daxCov.*q0.*q3.*(1.0./4.0);
t9 = t8-dayCov.*q0.*q3.*(1.0./4.0)-dazCov.*q1.*q2.*(1.0./4.0);
t10 = q0.^2;
t11 = q1.^2;
t12 = daxCov.*q1.*q2.*(1.0./4.0);
t13 = t12-dayCov.*q1.*q2.*(1.0./4.0)-dazCov.*q0.*q3.*(1.0./4.0);
t14 = dazCov.*q0.*q2.*(1.0./4.0);
t15 = t14-daxCov.*q0.*q2.*(1.0./4.0)-dayCov.*q1.*q3.*(1.0./4.0);
t16 = dayCov.*q0.*q1.*(1.0./4.0);
t17 = t16-daxCov.*q2.*q3.*(1.0./4.0)-dazCov.*q0.*q1.*(1.0./4.0);
Q = reshape([daxCov.*t11.*(1.0./4.0)+dayCov.*t5.*(1.0./4.0)+dazCov.*t4.*(1.0./4.0),t3,t7,t13,0.0,0.0,0.0,t3,daxCov.*t10.*(1.0./4.0)+dayCov.*t4.*(1.0./4.0)+dazCov.*t5.*(1.0./4.0),t9,t15,0.0,0.0,0.0,t7,t9,daxCov.*t4.*(1.0./4.0)+dayCov.*t10.*(1.0./4.0)+dazCov.*t11.*(1.0./4.0),t17,0.0,0.0,0.0,t13,t15,t17,daxCov.*t5.*(1.0./4.0)+dayCov.*t11.*(1.0./4.0)+dazCov.*t10.*(1.0./4.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[7,7]);
